image: node:lts

stages:
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

build_job:
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Building the application..."
    - npm run build
    - echo "Verifying build output..."
    - ls -la dist/
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - build_job
  script:
    - echo "Deploying to GitLab Pages..."
    - rm -rf public
    - mkdir -p public
    - cp -r dist/* public/
    - cp public/index.html public/404.html
    - echo "Verifying public directory content..."
    - ls -la public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH